name: Bug report
description: Create a report to help us improve
title: "[BUG]"
labels: bug
body:
  - type: markdown
    attributes:
      value: "Please fill out the following information:"
  - type: textarea          # <-- required interactive field
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe how to reproduce the issue
      placeholder: "1. ...\n2. ...\n3. ..."
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: "Describe what you expected to happen"
